### PR TITLE
Fix typos and code formatting in Docs

### PR DESCRIPTION
**Pull request by navidcy**
This PR fixes some typos + punctuation in the docs and enhances the code formatting in the inline examples provided in the docs.

### CODE REVIEW

**Comment by navidcy** [comment]
Sure! How do I do that?

**Comment by ilopezgp** [comment]
[This](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) is a useful guide to learn about squashing commits.

**Comment by navidcy** [comment]
I failed miserably :(

**Comment by ilopezgp** [comment]
From your local branch, can you do the following?

`git rebase -i HEAD~14`

Then squash all your commits except the first one that appears in the list. Once the rebasing is done, do

`git push --force`

**Pull request merged**
