### PR TITLE
JOSS draft paper

### PR DESCRIPTION
**Pull request by odunbar**
## Purpose
JOSS paper draft

PDF of paper from commit [e8d0820](https://github.com/CliMA/EnsembleKalmanProcesses.jl/pull/210/commits/e8d08204b373e3eeeeb16c10e11d9b3aa60b2ef2) is [here](https://github.com/CliMA/EnsembleKalmanProcesses.jl/files/9677987/paper.pdf)

### To find latest draft
1. Go to github Actions
2. Click on the latest action of `.github/workflows/draft-pdf.yml` on push to `orad/JOSS-draft` (will be the name of the latest commit)
3. Click on `paper` in the `Artifacts section`, this is a zip file containing the latest PDF

TODO:
- Adding EDMF description of use?
- Cloudy description / RF?
- readthroughs

### CODE REVIEW

**Comment by ilopezgp** [comment]
I suggested some changes to the latest Google drive version. Let me know how to proceed to merge those in here!

**Comment by eviatarbach** [comment]
Great work on this! I made a few edits, mostly for readability. Feel free to revert any that you don't like.

By the way, are you planning to add citations to all the CES-related papers in the last section? That would give strong evidence of the usefulness of the package.

**Comment by odunbar** [comment]
So the main issue is many of these papers - though using the precursor tools for this package, don't actually use the package for the results. But we could probably link them for further evidence.

**Comment by ilopezgp** [comment]
> So the main issue is many of these papers - though using the precursor tools for this package, don't actually use the package for the results. But we could probably link them for further evidence.

There is one more paper close to being submitted using this package, Anna's paper on EDMF microphysics. Can we reference papers in prep., or maybe just give a description?

**Pull request merged**
