### PR TITLE
Add localization documentation.

### PR DESCRIPTION
**Pull request by ilopezgp**
# PULL REQUEST

## Purpose and Content

- Document localization kernels.

### CODE REVIEW

**Comment by ilopezgp** [comment]
@eviatarbach let me know what you think of the docs so far, perhaps we can expand on it with the result from a few examples on a subsequent PR?

**Comment by eviatarbach** [comment]
Hi Ignacio,

Looks good to me! I was thinking I could add a little information about the idea behind SEC, but I could do that with a separate PR.

**Review by eviatarbach — APPROVED** [review]

**Comment by ilopezgp** [comment]
> Hi Ignacio,
> 
> Looks good to me! I was thinking I could add a little information about the idea behind SEC, but I could do that with a separate PR.

That is a good idea! Let's do it in a separate PR.

**Pull request merged**
