### PR TITLE
Update GitHub Actions workflows to use Julia 1.6.4

### LINKED ISSUE #79: Should we be building the Docs with Julia v1.6.4?
https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/f5eac9b77d503a598cb4655f4c07522ba986e317/.github/workflows/Docs.yml#L29

### PR DESCRIPTION
**Pull request by navidcy**
This PR changes the GitHub Actions workflows to use Julia v1.6.4 which is the new long-term support version.
Now the docs are being built with Julia v1.6.4 and the test run on v1.6.4 and on v1.7.

Closes #79

### CODE REVIEW

**Comment by jakebolewski** [comment]
LGTM

**Comment by navidcy** [comment]
@jakebolewski, I was trying to update the docs and Julia formatter yml files to use the long-term release Julia 1.6.4. But somehow the Docs GitHub Actions don't seem to work, i.e., it's not even get triggered.

Is it something related with my repo rights?

**Comment by jakebolewski** [comment]
Hmm, is it because the PR is a draft?

**Comment by jakebolewski** [comment]
@navidcy ah it is because of  https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/main/.github/workflows/Docs.yml#L11 
we need to add the Doc workflow file to that list

**Comment by navidcy** [comment]
OK. I also simplified the `Documenter.yml` a bit. @jakebolewski do all the changes seem OK?

**Comment by navidcy** [comment]
@jakebolewski, does this seem ok?
https://github.com/CliMA/EnsembleKalmanProcesses.jl/runs/4476427968?check_suite_focus=true

Post run actions/checkout@v2 seems stalled?

**Pull request merged**
