### PR TITLE
The great formatting.

### PR DESCRIPTION
**Pull request by ilopezgp**
Let's use the formatting that makes other CliMA packages look so nice.

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
Looks good to me. We probably want to add a `"format"` entry to the [bors toml file](https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/main/bors.toml#L3).

We could also use bors and add branch protection, it looks like.

**Comment by ilopezgp** [comment]
I added the `format` entry, but I am not sure how to add branch protection.

**Comment by charleskawczynski** [comment]
I can do that

**Comment by charleskawczynski** [comment]
Let's first try merging with bors, to make sure that we're passing that way.

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
