### PR TITLE
Udpdate module names to new convention.

### PR DESCRIPTION
**Pull request by ilopezgp**
Updates module names to follow the convention of module having the same name as the file where it is stored.

Also eliminates the EnsembleKalmanProcess module and structures the EnsembleKalmanProcess tests.

### CODE REVIEW

**Comment by ilopezgp** [comment]
Good suggestions, I will do that as well.

**Comment by ilopezgp** [comment]
Should be good to go now!

**Comment by odunbar** [comment]
LGTM! @ilopezgp merge when ready

**Review by odunbar — APPROVED** [review]

**Comment by ilopezgp** [comment]
Closed #13 .

**Pull request merged**
