### PR TITLE
implement Base.show for core types

### PR DESCRIPTION
**Pull request by haakon-e**
See #257 for details.

With this implementation, combining all the examples [here](https://clima.github.io/EnsembleKalmanProcesses.jl/dev/parameter_distributions/#ParameterDistribution-constructor) gives a vector that displays like this:
```julia
julia> combine_distributions([u; prior])
ParameterDistribution with 7 entries: 
'constrained_mvnormal' with Constraint[Bounds: (0, ∞), Bounds: (0, ∞), Bounds: (0, ∞)] over distribution Parameterized(FullNormal( dim: 3 μ: [1.0, 1.0, 1.0] Σ: [0.5 0.25 0.0; 0.25 0.5 0.25; 0.0 0.25 0.5] ) ) 
'constrained_sampled' with Constraint[Bounds: (10, 15), Bounds: (-∞, ∞)] over distribution Samples{Float64}([1.0 5.0 9.0 13.0; 3.0 7.0 11.0 15.0]) 
'Beta' with Constraint[Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞)] over distribution VectorOfParameterized{Beta{Float64}}(Beta{Float64}[Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0), Beta{Float64}(α=2.0, β=2.0)]) 
'point_seven' with Constraint[Bounds: (0.0, 1.0)] over distribution Parameterized(Normal{Float64}(μ=0.9581731745582243, σ=0.7851841275859747)) 
'upper bound' with Constraint[Bounds: (-∞, 5.0)] over distribution Parameterized(Normal{Float64}(μ=1.458006955602075, σ=0.03487311564634986)) 
'lower bound' with Constraint[Bounds: (-5.0, ∞)] over distribution Parameterized(Normal{Float64}(μ=1.740120034293624, σ=0.026311235124201148)) 
'no bound' with Constraint[Bounds: (-∞, ∞)] over distribution Parameterized(Normal{Float64}(μ=0.7, σ=0.15)) 
```

Individual constraints render like this:
```julia
julia> no_constraint()
Constraint{NoConstraint} with bounds (-∞, ∞)

julia> bounded_below(-5)
Constraint{BoundedBelow} with bounds (-5, ∞)

julia> bounded_above(-5)
Constraint{BoundedAbove} with bounds (-∞, -5)

julia> bounded(-5,5)
Constraint{Bounded} with bounds (-5, 5)
```

### CODE REVIEW

**Comment by haakon-e** [comment]
What do you think @odunbar? One downside of this implementation, particularly for bounds, is that new, custom structs may not contain enough information. Consider e.g. the affine constraint type from [examples](https://clima.github.io/EnsembleKalmanProcesses.jl/dev/parameter_distributions/#Example-combining-several-distributions):
```julia
julia> d2 = Samples([1.0 5.0 9.0 13.0; 3.0 7.0 11.0 15.0]) # 4 samples of 2D parameter space
Samples{Float64}([1.0 5.0 9.0 13.0; 3.0 7.0 11.0 15.0])

julia> transform = (x -> 3 * x + 14)
#13 (generic function with 1 method)

julia> jac_transform = (x -> 3)
#15 (generic function with 1 method)

julia> inverse_transform = (x -> (x - 14) / 3)
#17 (generic function with 1 method)

julia> abstract type Affine <: ConstraintType end

julia> c2 = [bounded(10, 15),
             Constraint{Affine}(transform, jac_transform, inverse_transform, nothing)]
2-element Vector{Constraint}:
 Constraint{Bounded} with bounds (10, 15)
 Constraint{Affine} with bounds (-∞, ∞)

julia> name2 = "constrained_sampled"
"constrained_sampled"

julia> u2 = ParameterDistribution(d2, c2, name2)
ParameterDistribution with 1 entries: 
'constrained_sampled' with Constraint[Bounds: (10, 15), Bounds: (-∞, ∞)] over distribution Samples{Float64}([1.0 5.0 9.0 13.0; 3.0 7.0 11.0 15.0]) 
```

Should I explicitly check for `NoConstraint`, `BoundedBelow`, `BoundedAbove` and `Bounded` when printing, and then print something more comprehensive if it's some other type?

**Comment by haakon-e** [comment]
btw, I got an error using some neat >v1.6 syntax:
```julia
(; distribution, constraint, name) = distributions

ERROR: LoadError: LoadError: syntax: invalid assignment location "; distribution, constraint, name" around /home/runner/work/EnsembleKalmanProcesses.jl/EnsembleKalmanProcesses.jl/src/ParameterDistributions.jl:435
[...]
```
so I changed it to be compatible... but maybe we should think about updating the version of our runners? Or are we explicitly wanting to support Julia 1.6 still?

**Comment by odunbar** [comment]
Looks Great! 

1. If users implement their own constraints, they have the option to add a `Dict` meta-data (currently the `nothing` in your constructor example). Unhelpfully we call this "bounds", but we could maybe have an option that if it not a predefined constraint, then display this. E.g
`Constraint{Affine}(transform, jac_transform, inverse_transform, Dict("linear" => 3, "const" => 14)`
Would display something like
`Constraint{Affine} with characterization (linear = 3, const = 14)`
We are providing a small convenience here, I wouldn't try to anticipate these unknown functions beyond what users wish to provide.

2. Thanks for noting the Julia 1.6 issue, I guess there is no explicit reason to support 1.6, except that we do. On the other hand, this is the first instance I've seen where we have a support problem, so perhaps we can leave it compatible for now until future refactors.

**Comment by haakon-e** [comment]
With your suggestion, the following is now outputted:
```julia
julia> c2 = [bounded(10, 15), Constraint{Affine}(transform, jac_transform, inverse_transform, Dict("linear" => 3, "const" => 14))]
2-element Vector{Constraint}:
 Constraint{Bounded} with bounds (10, 15)
 Constraint{Affine} with characterization ("linear" => 3, "const" => 14)
```

**Review by odunbar — APPROVED** [review]
LGTM! 

We can ignore codecov as it is not a sensible, so squash and merge, thanks!

**Pull request merged**
